// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AidCare2.Migrations
{
    [DbContext(typeof(AidCare2Context))]
    [Migration("20220506015235_added all views lol")]
    partial class addedallviewslol
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AidCare2.Models.donations", b =>
                {
                    b.Property<int>("donationsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("donationsID"), 1L, 1);

                    b.Property<string>("DonationsDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("donationsAmount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("membersID")
                        .HasColumnType("int");

                    b.HasKey("donationsID");

                    b.HasIndex("membersID");

                    b.ToTable("donations");
                });

            modelBuilder.Entity("AidCare2.Models.events", b =>
                {
                    b.Property<int>("eventsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("eventsID"), 1L, 1);

                    b.Property<string>("eventsDateTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eventsVenue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("eventsID");

                    b.ToTable("events");
                });

            modelBuilder.Entity("AidCare2.Models.members", b =>
                {
                    b.Property<int>("membersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("membersId"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("membersId");

                    b.ToTable("members");
                });

            modelBuilder.Entity("AidCare2.Models.donations", b =>
                {
                    b.HasOne("AidCare2.Models.members", null)
                        .WithMany("donations")
                        .HasForeignKey("membersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AidCare2.Models.members", b =>
                {
                    b.Navigation("donations");
                });
#pragma warning restore 612, 618
        }
    }
}
